function bif=ita_SII_BIF()
%return the literature values of the BIF according to ANSI S3.5-1997 
%Data can be accessed as object property eg. <bif.standard>
% Auto-generated by MATLAB on 04-Mar-2021 10:59:44

opts = spreadsheetImportOptions("NumVariables", 16);

% Specify sheet and range
opts.Sheet = "ANSI";
opts.DataRange = "A2:P19";

% Specify column names and types
opts.VariableNames = ["lowfreq", "highfreq", "centerfreq", "refinternalnoisespectrumlevel", "refspeechlevel", "standardtable3", "nonsensesyllabletestswheremostofEnglishphonemesoccur", "CID22", "NU6", "DiagRhymetest", "shortpassages", "SPIN", "Pavlovic87", "chen_2016_chinese_male", "chen_2016_chinese_female", "chen_2016_chinese_average","constant","extreme","bad_refcond"];
opts.VariableTypes = ["double","double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double","double","double"];

% Import the data
bif = readtable("import_funct_lit.xlsx", opts, "UseExcel", false);

end